# Generated by Django 6.0.6 on 2026-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_alter_booking_uuid_alter_feedback_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('unavailable', 'Unavailable')], max_length=20),
        ),
    ]
