# Generated by Django 6.0.6 on 2026-07-12 10:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_alter_rooms_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_images',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
